### ISSUE TITLE
localized country_select

### ISSUE THREAD

**Issue by pekeler** [carmen-ruby/carmen-rails#3]
How do you use country_select in a different language. I tried Carmen.i18n_backend.locale=:es but the select is still in English.

Thanks!

**Comment by jim** [comment]
This was an issue in [carmen](https://github.com/jim/carmen) where some attributes of regions were being cached and not updating when the locale changed. It is fixed in the master branch of that project.

FWIW my plan is to have carmen-rails hook into the default Rails i18n machinery, so that the Rails locale will be inherited by carmen.

I'm also going to add a locale menu to the demo app once that's done to demonstrate how to get everything working.
